# Generated by Django 4.2 on 2023-05-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bidded_at", models.DateTimeField(auto_now_add=True)),
                ("product_name", models.TextField()),
                ("bid_price", models.IntegerField()),
                ("bidder_name", models.TextField()),
                ("bidder_phone", models.TextField(max_length=11)),
                ("bidder_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.TextField()),
                ("product_name", models.TextField()),
                ("product_size", models.TextField()),
                ("buy_now", models.IntegerField()),
                ("current_price", models.IntegerField()),
                ("frame", models.TextField(default="X")),
                ("sold", models.BooleanField(default=False)),
            ],
        ),
    ]
